language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
script: make test
notifications:
  email: false
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/groups'
  matrix:
    - DJANGO='django>=1.6,<1.7'
    - DJANGO='django>=1.7,<1.8'
install:
  - psql -c 'CREATE DATABASE groups' -U postgres;
  - pip install -r requirements.txt --use-wheel
  - pip install $DJANGO --use-wheel
